[package]
name = "seichi-game-data-publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
async-trait = "0.1.68"
pbjson-types = "0.9.0"
prost = "0.14.0"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tonic = { version = "0.14.0", features = ["gzip"] }
tonic-prost = "0.14.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing = "0.1.37"
anyhow = "1.0.82"
envy = "0.4.2"
serde = "1.0.198"
tower-http = { version = "0.4.0", features = ["trace"] }
indexmap = "1.9.3"
